export const NODE_SHAPE = [
  { label: "Barrel", value: "barrel" },
  { label: "Concave Hexagon", value: "concave-hexagon" },
  { label: "Cut Rectangle", value: "cut-rectangle" },
  { label: "Diamond", value: "diamond" },
  { label: "Ellipse", value: "ellipse" },
  { label: "Heptagon", value: "heptagon" },
  { label: "Hexagon", value: "hexagon" },
  { label: "Octagon", value: "octagon" },
  { label: "Pentagon", value: "pentagon" },
  { label: "Rectangle", value: "rectangle" },
  { label: "Rhomboid", value: "rhomboid" },
  { label: "Round Diamond", value: "round-diamond" },
  { label: "Round Heptagon", value: "round-heptagon" },
  { label: "Round Hexagon", value: "round-hexagon" },
  { label: "Round Octagon", value: "round-octagon" },
  { label: "Round Pentagon", value: "round-pentagon" },
  { label: "Round Rectangle", value: "roundrectangle" },
  { label: "Round Tag", value: "round-tag" },
  { label: "Round Triangle", value: "round-triangle" },
  { label: "Star", value: "star" },
  { label: "Tag", value: "tag" },
  { label: "Triangle", value: "triangle" },
  { label: "Vee", value: "vee" },
];
