apiVersion: v1
kind: Service
metadata:
  name: graph-explorer
spec:
  selector:
    app: graph-explorer
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  sessionAffinity: None
  type: ClusterIP
