services:
  gremlin-server:
    image: tinkerpop/gremlin-server:latest
    ports: 
     - "8182:8182"
    environment:
      - gremlinserver.channelizer=org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer
    command: /opt/gremlin-server/sample/conf/gremlin-server-air-routes.yaml
    volumes:
      - ./sample:/opt/gremlin-server/sample