name: Build Docker image and publish to ECR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "ECR image tag type"
        required: false
        type: choice
        options:
          - "latest"
          - "release"
        default: "latest"
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p 'require("./package.json").version')" >> $GITHUB_OUTPUT

      - name: Get image tag
        id: get-image-tag
        env:
          IS_RELEASE: ${{ github.event_name == 'workflow_dispatch' && inputs.image_tag == 'release' }}
          VERSION: ${{ steps.package-version.outputs.version }}
        run: |
          if [ "$IS_RELEASE" = "true" ]; then
            echo "image_tag=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "image_tag=latest-SNAPSHOT" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ECR }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ECR }}
          role-duration-seconds: 3600
          role-session-name: ExplorerImageUpdate

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@376925c9d111252e87ae59691e5a442dd100ef6a # v2.1.3
        with:
          registry-type: public

      - name: Build, tag, and push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: neptune
          REPOSITORY: graph-explorer
          IMAGE_TAG: ${{ steps.get-image-tag.outputs.image_tag }}
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
          docker tag $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:sagemaker-$IMAGE_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:sagemaker-$IMAGE_TAG

      - name: Update latest tag for release
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.image_tag ==
          'release' }}
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: neptune
          REPOSITORY: graph-explorer
          IMAGE_TAG: ${{ steps.get-image-tag.outputs.image_tag }}
        run: |
          docker tag $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest
          docker tag $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:sagemaker-$IMAGE_TAG $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:sagemaker-latest
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:sagemaker-latest
