name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Review dependencies for vulnerabilities
        uses: actions/dependency-review-action@v4

  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: "package.json"

      - name: Install package and dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type, lint, and format checks
        run: pnpm checks

      - name: Run package tests with code coverage
        run: pnpm coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: unittests
